name: CI

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: ~

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Install
        run: bun install "--frozen-lockfile"
      - name: Test
        run: bun test